# Generated by Django 5.2.11 on 2026-02-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_tran_id', models.CharField(max_length=35)),
                ('original_merchant_tran_id', models.CharField(max_length=35)),
                ('original_bank_rrn', models.CharField(max_length=30)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
