# Generated by Django 5.2.11 on 2026-02-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmspartners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmsshipments',
            name='partner',
        ),
        migrations.AlterModelTable(
            name='wmsshipments',
            table='wmsshipments',
        ),
    ]
