# Generated by Django 5.2.11 on 2026-02-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmspartners', '0003_shipmentstatus_alter_wmsshipments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmsshipments',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='wmspartners.shipmentstatus'),
        ),
    ]
