# Generated by Django 5.2.11 on 2026-02-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmspartners', '0004_alter_wmsshipments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmsshipments',
            name='request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wmsshipments',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
